### ISSUE TITLE
How about the builtin SD Card?

### ISSUE THREAD

**Issue by hsnprojects** [arhi/EthernetSPI2#1]
Since both W5500 and SD Card using the same SPI interface, would it work with the built in SD Card along with W5500?

**Comment by arhi** [comment]
Not in SD mode because SD mode does not have "CS" pin. W5500 has CS pin so it is "enabled/selected" with GPIO2 so you can disable W5500 (or you can use any other GPIO, you can easily redefine CS)

If you use the SD card in SPI mode then you should be able to use it as then HS2_DATA2 is not used, HS2_DATA3 is CS for the SD card, HS2_CMD is MOSI and HS2_DATA0 is MISO. Problem is I'm using HS2_DATA3 (GPIO13) as MOSI for the W5500 so "as is" it will not work. 

If SPI2 MOSI (HSPI_MOSI) is remapped to another pin it should work but tbh I have no clue how to do that nor if it can be done at all.
